name: 'CI setup'
description: 'Setup pnpm and node'

inputs:
  package-manager-cache:
    description: 'Enable pnpm cache in setup-node'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v6
    - name: Setup node.js
      uses: actions/setup-node@v6
      with:
        # https://github.com/changesets/changesets/issues/2115
        node-version: '24.16.0'
        registry-url: 'https://registry.npmjs.org'
        package-manager-cache: ${{ inputs.package-manager-cache }}
    - name: Install dependencies
      run: pnpm install
      shell: bash
