// ⚠️  AUTO-GENERATED by scripts/gen-props-objects.mjs — DO NOT EDIT.
// Regenerate with `pnpm codegen`; CI verifies it is current with `pnpm codegen:check`.
//
// Runtime prop-declaration factories mirroring the NodeProps / EdgeProps / ConnectionLineProps interfaces,
// for JS users who cannot write `defineProps<NodeProps<T>>()` (a TS-only macro form).
// Each entry derives its type from the source interface via indexed access, so field type changes
// need no regeneration — only added/removed fields or optionality changes do.

import type { ConnectionLineProps, Edge, EdgeProps, Node, NodeProps } from './types';
import { propOf } from './utils/prop-of';

export function nodeProps<NodeType extends Node = Node>() {
  return {
    data: propOf<NodeProps<NodeType>['data']>(true),
    deletable: propOf<NodeProps<NodeType>['deletable']>(true),
    dragHandle: propOf<NodeProps<NodeType>['dragHandle']>(),
    draggable: propOf<NodeProps<NodeType>['draggable']>(true),
    dragging: propOf<NodeProps<NodeType>['dragging']>(true),
    height: propOf<NodeProps<NodeType>['height']>(),
    id: propOf<NodeProps<NodeType>['id']>(true),
    isConnectable: propOf<NodeProps<NodeType>['isConnectable']>(true),
    parentId: propOf<NodeProps<NodeType>['parentId']>(),
    positionAbsoluteX: propOf<NodeProps<NodeType>['positionAbsoluteX']>(true),
    positionAbsoluteY: propOf<NodeProps<NodeType>['positionAbsoluteY']>(true),
    selectable: propOf<NodeProps<NodeType>['selectable']>(true),
    selected: propOf<NodeProps<NodeType>['selected']>(true),
    sourcePosition: propOf<NodeProps<NodeType>['sourcePosition']>(),
    targetPosition: propOf<NodeProps<NodeType>['targetPosition']>(),
    type: propOf<NodeProps<NodeType>['type']>(true),
    width: propOf<NodeProps<NodeType>['width']>(),
    zIndex: propOf<NodeProps<NodeType>['zIndex']>(true),
  };
}

export function edgeProps<EdgeType extends Edge = Edge>() {
  return {
    animated: propOf<EdgeProps<EdgeType>['animated']>(),
    curvature: propOf<EdgeProps<EdgeType>['curvature']>(),
    data: propOf<EdgeProps<EdgeType>['data']>(),
    deletable: propOf<EdgeProps<EdgeType>['deletable']>(),
    id: propOf<EdgeProps<EdgeType>['id']>(true),
    interactionWidth: propOf<EdgeProps<EdgeType>['interactionWidth']>(),
    label: propOf<EdgeProps<EdgeType>['label']>(),
    labelBgBorderRadius: propOf<EdgeProps<EdgeType>['labelBgBorderRadius']>(),
    labelBgPadding: propOf<EdgeProps<EdgeType>['labelBgPadding']>(),
    labelBgStyle: propOf<EdgeProps<EdgeType>['labelBgStyle']>(),
    labelShowBg: propOf<EdgeProps<EdgeType>['labelShowBg']>(),
    labelStyle: propOf<EdgeProps<EdgeType>['labelStyle']>(),
    markerEnd: propOf<EdgeProps<EdgeType>['markerEnd']>(),
    markerStart: propOf<EdgeProps<EdgeType>['markerStart']>(),
    reconnectable: propOf<EdgeProps<EdgeType>['reconnectable']>(),
    selectable: propOf<EdgeProps<EdgeType>['selectable']>(),
    selected: propOf<EdgeProps<EdgeType>['selected']>(),
    source: propOf<EdgeProps<EdgeType>['source']>(true),
    sourceHandleId: propOf<EdgeProps<EdgeType>['sourceHandleId']>(),
    sourcePosition: propOf<EdgeProps<EdgeType>['sourcePosition']>(true),
    sourceX: propOf<EdgeProps<EdgeType>['sourceX']>(true),
    sourceY: propOf<EdgeProps<EdgeType>['sourceY']>(true),
    style: propOf<EdgeProps<EdgeType>['style']>(),
    target: propOf<EdgeProps<EdgeType>['target']>(true),
    targetHandleId: propOf<EdgeProps<EdgeType>['targetHandleId']>(),
    targetPosition: propOf<EdgeProps<EdgeType>['targetPosition']>(true),
    targetX: propOf<EdgeProps<EdgeType>['targetX']>(true),
    targetY: propOf<EdgeProps<EdgeType>['targetY']>(true),
    type: propOf<EdgeProps<EdgeType>['type']>(),
  };
}

export function connectionLineProps<NodeType extends Node = Node>() {
  return {
    connectionStatus: propOf<ConnectionLineProps<NodeType>['connectionStatus']>(true),
    fromHandle: propOf<ConnectionLineProps<NodeType>['fromHandle']>(true),
    fromNode: propOf<ConnectionLineProps<NodeType>['fromNode']>(true),
    fromPosition: propOf<ConnectionLineProps<NodeType>['fromPosition']>(true),
    fromX: propOf<ConnectionLineProps<NodeType>['fromX']>(true),
    fromY: propOf<ConnectionLineProps<NodeType>['fromY']>(true),
    markerEnd: propOf<ConnectionLineProps<NodeType>['markerEnd']>(),
    markerStart: propOf<ConnectionLineProps<NodeType>['markerStart']>(),
    pointer: propOf<ConnectionLineProps<NodeType>['pointer']>(true),
    toHandle: propOf<ConnectionLineProps<NodeType>['toHandle']>(true),
    toNode: propOf<ConnectionLineProps<NodeType>['toNode']>(true),
    toPosition: propOf<ConnectionLineProps<NodeType>['toPosition']>(true),
    toX: propOf<ConnectionLineProps<NodeType>['toX']>(true),
    toY: propOf<ConnectionLineProps<NodeType>['toY']>(true),
  };
}
