name: Storybook Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: 'Storybook Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-checks
      - name: Install Chromium
        run: pnpm --filter storybook-react exec playwright install --with-deps chromium
      - name: Run Storybook tests
        run: pnpm test:storybook
